# Generated by Django 4.2 on 2023-05-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZipName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_name', models.TextField(verbose_name='Zip Name')),
                ('entry_added_on', models.DateTimeField(auto_now_add=True, verbose_name='Entry added on')),
            ],
        ),
        migrations.CreateModel(
            name='FileUploadDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(verbose_name='File name')),
                ('session_id', models.IntegerField(verbose_name='Upload Session ID')),
                ('offset', models.IntegerField(verbose_name='Offset')),
                ('entry_added_on', models.DateTimeField(auto_now_add=True, verbose_name='Entry added on')),
                ('zip_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_sessions.zipname')),
            ],
        ),
    ]
