# Generated by Django 4.2 on 2023-05-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploaddetail',
            name='session_id',
            field=models.TextField(verbose_name='Upload Session ID'),
        ),
    ]
