# Generated by Django 4.2 on 2023-04-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, verbose_name='Name')),
                ('file_description', models.TextField(max_length=300, verbose_name='Description')),
                ('file', models.CharField(max_length=500, verbose_name='Download URL')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded on')),
                ('expires_on', models.CharField(max_length=100, verbose_name='Expires on')),
            ],
        ),
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='URL Id')),
                ('long_url', models.TextField(verbose_name='Long URL')),
                ('short_url', models.TextField(verbose_name='Short URL')),
                ('visited', models.IntegerField(default=0, verbose_name='Visitors')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
            ],
        ),
    ]
